@startuml
skinparam linetype ortho
skinparam entity {
    BackgroundColor White
    BorderColor Black
    ArrowColor Black
}

' --- 1. TABEL USER/ADMIN (FIREBASE AUTHENTICATION) ---
entity "Admin" as admin {
    *uid : String <<PK>>
    --
    email : String
    password : String
    update_at : DateTime
}

' --- 2. TABEL STATUS SENSOR (REALTIME DATABASE) ---
' Ini merepresentasikan node "Virtual_Object" di Firebase
entity "Virtual_Object" as object {
    *node_key : String <<PK>>
    --
    status_sekarang : String
    ' (Isinya: "ON" atau "OFF")
    waktu_update : String
    ' (Waktu saat sensor terakhir mendeteksi tangan)
    waktu_mulai_online : String
    ' (Waktu saat ESP32 pertama kali dinyalakan)
}

' --- HUBUNGAN ---

' Admin memantau Objek lewat Dashboard
' One-to-One (Satu Admin memantau Satu Sistem Dashboard)
admin ||..|| object : "monitoring"

@enduml