@startuml
!theme plain
skinparam defaultTextAlignment center

' --- DEFINISI STYLE ---
skinparam activity {
    BackgroundColor White
    BorderColor Black
    ArrowColor Black
    FontName Arial
}

start

' === BAGIAN HARDWARE (ESP32) ===

' Simbol Jajar Genjang = INPUT
:User Mendekatkan Tangan/Objek<
note right: Input Fisik

' Simbol Jajar Genjang = INPUT
:Sensor IR Obstacle Mendeteksi (LOW)<
note right: Input Hardware

' Simbol Persegi = PROSES
:ESP32 Membaca Pin Digital]

' Simbol Persegi = PROSES (Baru: Ambil Jam)
:Ambil Waktu dari Server NTP (Internet)]

' Simbol Belah Ketupat = DECISION
if (Apakah Ada Halangan?) then (Tidak / HIGH)
    ' Simbol Persegi = PROSES
    :Set Status = OFF]
else (Ya / LOW)
    ' Simbol Persegi = PROSES
    :Set Status = ON]
endif

' Simbol Tabung = DATABASE
:Simpan Status & Waktu ke Firebase|
note right: Cloud Database

' === BAGIAN WEBSITE (SOFTWARE) ===

' Simbol Jajar Genjang = INPUT (Web Menerima)
:Website Menerima Perubahan Data<

' Simbol Belah Ketupat = DECISION
if (Status == ON?) then (Ya)
    ' Simbol Persegi = PROSES
    :Ubah Visual Lampu = NYALA (Hijau)]
else (Tidak)
    :Ubah Visual Lampu = MATI (Hitam/abu-abu)]
endif

' Simbol Persegi = PROSES
:Konversi Timestamp jadi Jam Terbaca]

' Simbol Jajar Genjang = OUTPUT (Tampilan)
:Tampilkan Status & Jam di Monitor/
note right: Output Visual

stop
@enduml