@startuml
left to right direction
skinparam packageStyle rectangle

actor "User (Fisik)" as user
actor "Admin (Web)" as admin

rectangle "Sistem Monitoring IoT" {
  
  ' --- Bagian Hardware (Otomatis oleh Sistem) ---
  usecase "Memicu Sensor (Gerakan Tangan)" as UC1
  usecase "Update Status & Waktu ke Firebase" as UC2

  ' --- Bagian Website (Interaksi Admin) ---
  usecase "Login Admin" as UC3
  usecase "Logout" as UC4
  usecase "Akses Dashboard Monitoring" as UC8
  
  ' Fitur di dalam Dashboard
  usecase "Lihat Status Real-time (Lampu)" as UC5
  usecase "Lihat Waktu Update (NTP)" as UC6
}

' === RELASI HARDWARE ===
user --> UC1
UC1 ..> UC2 : <<include>> (Otomatis)

' === RELASI WEBSITE ===
' 1. Admin masuk ke sistem
admin --> UC3 : Input Email & Pass

' 2. Aturan Dashboard
' (Membuka Dashboard otomatis butuh Login)
UC3 ..> UC8 : <<include>> 

' (Di dalam Dashboard terdapat 3 fitur utama)
UC8 ..> UC5 : <<include>>
UC8 ..> UC6 : <<include>>

' 3. Logout dilakukan dari dalam Dashboard
UC4 .> UC3 : <<extend>>

@enduml